### ISSUE TITLE
add_case in python seems not to be working. 

### ISSUE THREAD

**Issue by niquefa** [niquefaDiego/problem-solving#14]
I got this output:

➜  problem-solving git:(main) ✗ ./add_case 4
Adding case 4
 -> workspace/cf230A/cases/4.in
 -> workspace/cf230A/cases/4.out
ERROR: command not found: code
Install VSCode to automatically open the created files in VSCode:
 -> https://code.visualstudio.com/
When using Windows Subsystem for Linux you also need to install:
 -> https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
➜  problem-solving git:(main) ✗

But no 4.in nor 4.out files were added.

**Comment by niquefaDiego** [comment]
Just fixed the issue in [this PR](https://github.com/niquefaDiego/problem-solving/pull/15)
